### ISSUE TITLE
Emerge warning opentmpfiles EAPI 6 not supported

### ISSUE THREAD

**Issue by Nopel2020** [KenjiBrown/without-systemd#4]
I don't have opentmpfiles installed, since I am using hardenedtmpfiles instead. But since yesterday, every single emerge command gives the following warning:
```
 * ERROR: sys-apps/opentmpfiles-0.2::without-systemd failed (depend phase):
 *   prefix: EAPI 6 not supported
```

Indeed I see that all opentmpfiles ebuilds use the obsolete EAPI 6. If I delete the /var/db/repos/without-systemd/sys-apps/opentmpfiles directory, the warning disappears. But every time I do `emerge --sync`, the ebuilds come back and so does the annoying warning.

Could you update the ebuild, or just drop opentmpfiles from the repository completely? Thanks!

**Comment by KenjiBrown** [comment]
Yesterday I sent a fix for this EAPI 6 error.
Can you try again `emerge update` and let me know if the EAPI 6 error keeps showing?

**Comment by Nopel2020** [comment]
It worked! I'm no longer getting the warning.

Thanks!
